Fix memory errors in udev-device-parent-with-subsystem-devtype
It seems that the premature deallocation of udev causes the following
problem:

Error: segmentation violation
        ...
        Call history:
        udev.scm:267: udev-new
        udev.scm:268: udev-device-syspath
        udev.scm:269: %udev-device-new-from-syspath
        udev.scm:173: ##sys#make-c-string
        udev.scm:179: ##sys#make-c-string
        udev.scm:179: ##sys#make-c-string
        udev.scm:274: %udev-unref
        udev.scm:275: make-udev-device          <--

Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>